name: Enterprise CI Workflow

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
jobs:
  build:
    runs-on: runner-scale-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Hello
        run: echo "Hello, World!"
      - name: Current Date
        run: date
      - name: List all files
        run: ls -la