name: CI workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Hello
        run: echo "Hello, World!"
      - name: Current Date
        run: date
      - name: List all files
        run: ls -la
